---
# tasks file for sa-ruby

  - name: Ruby | package dependencies + cache update
    apt: pkg={{ item }} state=present force="yes"  update_cache="yes"
    with_items: "{{needed_packages | default([])}}"
    become: yes

  - include: 'ch_ruby.yml'

  - include: 'ruby_install.yml'

  - include: 'ruby.yml'
